// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using autobagaz.Models;

namespace autobagaz.Migrations
{
    [DbContext(typeof(AutobagazContext))]
    [Migration("20190730065945_Autobagazhniki")]
    partial class Autobagazhniki
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("autobagaz.Autobagazhnik", b =>
                {
                    b.Property<int>("AUTOBAGAZHIK_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AUTOBAGAZHIK_DESCRIPTION");

                    b.Property<string>("AUTOBAGAZHIK_FILE_NAME");

                    b.Property<string>("AUTOBAGAZHIK_FILE_PATH");

                    b.Property<string>("AUTOBAGAZHIK_NAME");

                    b.HasKey("AUTOBAGAZHIK_ID");

                    b.ToTable("AUTOBAGAZHIK");
                });

            modelBuilder.Entity("autobagaz.AutobagazhnikReelings", b =>
                {
                    b.Property<int>("AUTOBAGAZHIK_REELINGS_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AUTOBAGAZHIK_REELINGS_DESCRIPTION");

                    b.Property<string>("AUTOBAGAZHIK_REELINGS_FILE_NAME");

                    b.Property<string>("AUTOBAGAZHIK_REELINGS_FILE_PATH");

                    b.Property<string>("AUTOBAGAZHIK_REELINGS_NAME");

                    b.HasKey("AUTOBAGAZHIK_REELINGS_ID");

                    b.ToTable("AUTOBAGAZHIK_REELINGS");
                });

            modelBuilder.Entity("autobagaz.AutobagazhnikShtatnye", b =>
                {
                    b.Property<int>("AUTOBAGAZHIK_SHTATNYE_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AUTOBAGAZHIK_SHTATNYE_DESCRIPTION");

                    b.Property<string>("AUTOBAGAZHIK_SHTATNYE_FILE_NAME");

                    b.Property<string>("AUTOBAGAZHIK_SHTATNYE_FILE_PATH");

                    b.Property<string>("AUTOBAGAZHIK_SHTATNYE_NAME");

                    b.HasKey("AUTOBAGAZHIK_SHTATNYE_ID");

                    b.ToTable("AUTOBAGAZHIK_SHTATNYE");
                });

            modelBuilder.Entity("autobagaz.AutobagazhnikSmooth", b =>
                {
                    b.Property<int>("AUTOBAGAZHIK_SMOOTH_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AUTOBAGAZHIK_SMOOTH_DESCRIPTION");

                    b.Property<string>("AUTOBAGAZHIK_SMOOTH_FILE_NAME");

                    b.Property<string>("AUTOBAGAZHIK_SMOOTH_FILE_PATH");

                    b.Property<string>("AUTOBAGAZHIK_SMOOTH_NAME");

                    b.HasKey("AUTOBAGAZHIK_SMOOTH_ID");

                    b.ToTable("AUTOBAGAZHIK_SMOOTH");
                });

            modelBuilder.Entity("autobagaz.AutobagazhnikVodostok", b =>
                {
                    b.Property<int>("AUTOBAGAZHIK_VODOSTOK_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AUTOBAGAZHIK_VODOSTOK_DESCRIPTION");

                    b.Property<string>("AUTOBAGAZHIK_VODOSTOK_FILE_NAME");

                    b.Property<string>("AUTOBAGAZHIK_VODOSTOK_FILE_PATH");

                    b.Property<string>("AUTOBAGAZHIK_VODOSTOK_NAME");

                    b.HasKey("AUTOBAGAZHIK_VODOSTOK_ID");

                    b.ToTable("AUTOBAGAZHIK_VODOSTOK");
                });
#pragma warning restore 612, 618
        }
    }
}
