<?php
$porogiarray = [
	[
	'id' => 'BlackFordKuga2013',
	'name' => 'Порог-площадка Black для Ford Kuga 2013+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BlackFordKuga2013.jpg" alt="BlackFordKuga2013">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '12 050 рублей',
	],
  [
	'id' => 'BmwFordKuga2013',
	'name' => 'ПОРОГ-ПЛОЩАДКА BMW-STYLE D ДЛЯ FORD KUGA 2013+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BmwFordKuga2013.jpg" alt="BmwFordKuga2013">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '13 530 рублей',
	],
  [
	'id' => 'PremiumFordKuga2013',
	'name' => 'ПОРОГ-ПЛОЩАДКА PREMIUM ДЛЯ FORD KUGA 2013+',
  'img' => '<img class="img good__img" src="/content/porogi/img/PremiumFordKuga2013.jpg" alt="PremiumFordKuga2013">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '15 200 рублей',
	],
  [
	'id' => 'BlackHyundaiTucson2015',
	'name' => 'ПОРОГ-ПЛОЩАДКА BLACK ДЛЯ HYUNDAI TUCSON 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BlackHyundaiTucson2015.jpg" alt="BlackHyundaiTucson2015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '12 050 рублей',
	],
  [
	'id' => 'BmwHyundaiTucson2015',
	'name' => 'ПОРОГ-ПЛОЩАДКА BMW-STYLE D ДЛЯ HYUNDAI TUCSON 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BmwHyundaiTucson2015.jpg" alt="BmwHyundaiTucson2015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '13 530 рублей',
	],
  [
	'id' => 'PremiumHyundaiTucson2015',
	'name' => 'Порог-площадка Premium для Hyundai Tucson 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/PremiumHyundaiTucson2015.jpg" alt="PremiumHyundaiTucson2015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '15 200 рублей',
	],
  [
	'id' => 'BlackLadaXray2016',
	'name' => 'Порог-площадка Black для Lada XRay 2016+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BlackLadaXray2016.jpg" alt="BlackLadaXray2016">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '12 050 рублей',
	],
  [
	'id' => 'BmwLadaXray2016',
	'name' => 'Порог-площадка BMW-Style D для Lada XRay 2016+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BmwLadaXray2016.jpg" alt="BmwLadaXray2016">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '13 530 рублей',
	],
  [
	'id' => 'PremiumLadaXray2016',
	'name' => 'Порог-площадка Premium для Lada XRay 2016+',
  'img' => '<img class="img good__img" src="/content/porogi/img/PremiumLadaXray2016.jpg" alt="PremiumLadaXray2016">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '15 200 рублей',
	],
  [
	'id' => 'BlackMitsubishiL2002015',
	'name' => 'Порог-площадка Black для Mitsubishi L200 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BlackMitsubishiL2002015.jpg" alt="BlackMitsubishiL2002015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '12 050 рублей',
	],
  [
	'id' => 'BmwMitsubishiL2002015',
	'name' => 'Порог-площадка Bmw-Style D для Mitsubishi L200 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/BmwMitsubishiL2002015.jpg" alt="BmwMitsubishiL2002015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '13 530 рублей',
	],
  [
	'id' => 'PremiumMitsubishiL2002015',
	'name' => 'Порог-площадка Premium для Mitsubishi L200 2015+',
  'img' => '<img class="img good__img" src="/content/porogi/img/PremiumMitsubishiL2002015.jpg" alt="PremiumMitsubishiL2002015">',
	'material' => 'Алюминий',
	'type' => 'Площадка',
	'price' => '15 200 рублей',
	],
];


