<?php
//Велокрепления на крышу 
$velokrysha = [
		[
		'id' => 'vk1',
		'name' => 'Велокрепление Amos',
		'desc' => 'Велокрепление Amos для перевозки велосипеда на крыше автомобиля имеет очень простую, но в то же время довольна надежную конструкцию, которая позволяет закрепить велосипед на крыше Вашего автомобиля, потратив при этом "минимум" денег.',
		'img1' => '<img class="img_main" src="/images/velo/krysha/amos_1.jpg" srcset="/images/velo/krysha/amos_1.jpg 200w" alt="amos" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/krysha/amos_2.jpg" srcset="/images/velo/krysha/amos_2.jpg 200w" alt="amos" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 2 000 рублей',
		],
		[
		'id' => 'vk2',
		'name' => 'Велосипедное крепление Люкс',
		'desc' => 'Велосипедное крепление Lux Bike - это крепление для перевозки велосипеда на крыше автомобиля. Крепление устанавливается на любые виды поперечин (прямоугольные, аэродинамические), возможна перевозка велосипедов с диаметром рамы от 20 до 65 мм. Вам не потребуются дополнительные инструменты для его установки. Велокрепление Lux Bike (Люкс Байк) выполнено из стали и предназначено для транспортировки одного велосипеда. Велокрепление Lux Bike (Люкс Байк) комплектуется специальным замком, предотвращающим кражу вашего велосипеда.',
		'img1' => '<img class="img_main" src="/images/velo/krysha/lux_bike_1.jpg" srcset="/images/velo/krysha/lux_bike_1.jpg 200w" alt="lux bike" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/krysha/lux_bike_2.jpg" srcset="/images/velo/krysha/lux_bike_2.jpg 200w" alt="lux bike" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 3 000 рублей',
		],
		[
		'id' => 'vk3',
		'name' => 'Велокрепление Thule 532',
		'desc' => 'Крепление для велосипедов, устанавливаемое на крыше Простые и функциональные крепления для велосипедов, удовлетворяющие всем основным условиям:',
		'img1' => '<img class="img_main" src="/images/velo/krysha/thule_532_1.jpg" srcset="/images/velo/krysha/thule_532_1.jpg 200w" alt="Thule 532" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/krysha/thule_532_2.jpg" srcset="/images/velo/krysha/thule_532_2.jpg 200w" alt="Thule 532" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 5 000 рублей',
		],
		[
		'id' => 'vk4',
		'name' => 'Велокрепление Thule 591/598',
		'desc' => 'Велокрепление Thule 591/598 снабжено совершенно новой конструкцией само регулируемого держателя рамы велосипеда, которое позволит Вам быстро и легко закрепить велосипед на багажнике и выгрузить его. Все крепления велобагажника Thule ProRide 591/598 расположены на уровне крыши - Вам не придется тянуться чтобы установить багажник и закрепить/снять велосипед.',
		'img1' => '<img class="img_main" src="/images/velo/krysha/thule_591_1.jpg" srcset="/images/velo/krysha/thule_591_1.jpg 200w" alt="Thule 591/598" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/krysha/thule_591_2.jpg" srcset="/images/velo/krysha/thule_591_2.jpg 200w" alt="Thule 591/598" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 8 000 рублей',
		],
]; 
//Велокрепления на фаркоп
$velofarkop = [
		[
		'id' => 'vf1',
		'name' => 'Велокрепление Amos',
		'desc1' => 'Велокрепление Amos для 3-х велосипедов на фаркоп</b> – это превосходная разработка польской фирмы AMOS (АМОС) для перевозки трех велоспедов, которое сочетает в себе высокое качество и приемлемую цену, а также превосходный дизайн и простоту установки на ваш автомобиль.',
		'desc2' => 'Крепление Amos устанавливается на фаркоп автомобиля, а затем надежно закрепляется на нем. Для фиксации велосипедов предусмотрены специальные ремешки, которые позволяют надежно закрепить ваши велосипеды, и не беспокоится за них.',
		'img1' => '<img class="img_main" src="/images/velo/farkop/amos_1.jpg" srcset="/images/velo/farkop/amos_1.jpg 200w" alt="amos" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/farkop/amos_2.jpg" srcset="/images/velo/farkop/amos_2.jpg 200w" alt="amos" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 4 500 рублей',
		],
		[
		'id' => 'vf2',
		'name' => 'Велокрепление Thule Xpress 970',
		'desc' => 'Велокрепление Thule Xpress 970 предназначено для установки на фаркоп и способно перевозить до 2-х велосипедов одновременно. Крепежный механизм Thule 970 строго соответствует стандартам ISO, что избавляет Вас от необходимости предварительной подгонки креплений. Thule Xpress 970 является одним из самых простых велобагажников для перевозки велосипедов на фаркопе.',
		'img1' => '<img class="img_main" src="/images/velo/farkop/Thule_Xpress_970_1.jpg" srcset="/images/velo/farkop/Thule_Xpress_970_1.jpg 200w" alt="Thule Xpress 970" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/velo/farkop/Thule_Xpress_970_2.jpg" srcset="/images/velo/farkop/Thule_Xpress_970_2.jpg 200w" alt="Thule Xpress 970" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'price' => 'Цена 6 500 рублей',
		],
]; 
//Лыжные крепления
$lyzhi = [
		[
		'id1' => 'amos34',
		'id2' => 'amos56',
		'name1' => 'Лыжное крепление Amos для 3-4 пар лыж',
		'name2' => 'Лыжное крепление Amos для 5-6 пар лыж',
		'title' => 'Лыжное крепление Amos',
		'desc' => 'Лыжное крепление закрывается на ключ. Материал сталь, порошковая окраска, пластик, резина. Цвет черный, серебро.',
		'img' => '<img class="img_main" src="/images/lyzhi/amos.jpg" srcset="/images/lyzhi/amos.jpg 400w" alt="amos" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'desc34' => 'Вариант для 3-4-х пар лыж/2 сноуборда (40 см)',
		'price34' => '2 700 рублей',
		'desc56' => 'Вариант для 5-6 пар лыж/4 сноуборда (60 см)',
		'price56' => '3 700 рублей',
		],
		[
		'id1' => 'atlant34',
		'id2' => 'atlant56',
		'name1' => 'Лыжное крепление Атлант для 3-4 пар лыж',
		'name2' => 'Лыжное крепление Атлант для 5-6 пар лыж',
		'title' => 'Лыжное крепление Атлант',
		'desc' => 'Атлант, СПб. Лыжное крепление закрывается на секретку. Материал Алюминий, пластик, резина.',
		'img' => '<img class="img_main" src="/images/lyzhi/atlant.jpg" srcset="/images/lyzhi/atlant.jpg 300w" alt="atlant" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'desc34' => 'Вариант для 3-4-х пар лыж/2 сноуборда (40 см)',
		'price34' => ' 4 200 рублей',
		'desc56' => 'Вариант для 5-6 пар лыж/4 сноуборда (60 см)',
		'price56' => ' 5 200 рублей',
		],
		[
		'id1' => 'montblanc34',
		'id2' => 'montblanc56',
		'name1' => 'Лыжное крепление Mont Blanc для 3-4 пар лыж',
		'name2' => 'Лыжное крепление Mont Blanc для 5-6 пар лыж',
		'title' => 'Лыжное крепление Mont Blanc',
		'desc' => 'Mont Blanc, Швеция. Материал Алюминий, сталь, порошковая окраска, пластик, резина.',
		'img' => '<img class="img_main" src="/images/lyzhi/mont_blanc.jpg" srcset="/images/lyzhi/mont_blanc.jpg 300w" alt="mont blanc" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'desc34' => 'Вариант для 3-4-х пар лыж/2 сноуборда (40 см)',
		'price34' => ' 7 000 рублей',
		'desc56' => 'Вариант для 5-6 пар лыж/4 сноуборда (60 см)',
		'price56' => ' 8 000 рублей',
		],
		[
		'id1' => 'thule34',
		'id2' => 'thule56',
		'name1' => 'Лыжное крепление Thule для 3-4 пар лыж',
		'name2' => 'Лыжное крепление Thule для 5-6 пар лыж',
		'title' => 'Лыжное крепление Thule',
		'desc' => 'Thule, Швеция. Материал алюминий, пластик, резина.',
		'img' => '<img class="img_main" src="/images/lyzhi/thule.jpg" srcset="/images/lyzhi/thule.jpg 200w" alt="thule" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'desc34' => 'Модель 726: для 3-4-х пар лыж/2 сноуборда (40 см)',
		'price34' => ' 7 000 рублей',
		'desc56' => 'Модель 727: для 5-6 пар лыж/4 сноуборда (60 см)',
		'price56' => ' 8 000 рублей',
		],
		[
		'id' => 'xtender',
		'name' => 'Thule XTENDER для перевозки 6-ти пар лыж',
		'desc' => 'Производство Швеция. Выдвигается в сторону, позволяя загружать и разгружать лыжи и не тянуться при этом через автомобиль, пачкая одежду.',
		'img1' => '<img class="img_main" src="/images/lyzhi/thule_xtender_1.jpg" srcset="/images/lyzhi/thule_xtender_1.jpg 150w" alt="Thule XTENDER" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img2' => '<img class="img_main" src="/images/lyzhi/thule_xtender_2.jpg" srcset="/images/lyzhi/thule_xtender_2.jpg 150w" alt="Thule XTENDER" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'img3' => '<img class="img_main" src="/images/lyzhi/thule_xtender_3.jpg" srcset="/images/lyzhi/thule_xtender_3.jpg 150w" alt="Thule XTENDER" sizes="(max-width: 2000px) 150px, 300px, 350px">',
		'descprice' => 'Доступно в варианте для 5-6 пар лыж/4 сноуборда (60 см)',
		'price' => ' 12 000 рублей',
		],
];
//Браслеты противоскольжения
$braslet = [
	'id1' => 'r12',
	'id2' => 'r16',
	'id3' => 'gazel',
	'name1' => 'Браслет противоскольжения R12-15',
	'name2' => 'Браслет противоскольжения R16-22,5',
	'name3' => 'Браслет противоскольжения для газелей',
	'title' => 'Браслеты противоскольжения',
	'desc' => 'Всесезонные, всепогодные. Устанавливаются без наезда, домкрата и инструмента в 1 минуту. Даже для полного привода достаточно 2-х браслетов. Отличный подарок активным автолюбителям.',
	'img' => '<img class="img_main" src="/images/braslets/braslet.jpg" srcset="/images/braslets/braslet.jpg 500w" alt="braslet" sizes="(max-width: 2000px) 150px, 300px, 350px">',
	'desc1' => 'R12-R15',
	'price1' => '500рублей/штука',
	'desc2' => 'R16-R22,5',
	'price2' => '1000 рублей/штука',
	'desc3' => 'Вариант для газелей',
	'price3' => 'от 1200 рублей/штука',
]; ?>