@csrf
@if (isset($product)) @method('PUT') @endif

@php
    $bikeRack = isset($product) ? $product->bikeRack : null;
    $selectedManufacturerId = (string) old('manufacturer_id', $bikeRack?->manufacturer_id ?? '');
@endphp

@include('admin.partials.help', ['title' => 'Заполнение велокрепления', 'text' => 'Заполните данные для карточки товара и каталога. Велокрепления имеют универсальную совместимость и не проверяются по автомобилю.', 'items' => ['Адрес страницы можно оставить пустым — он сформируется из названия.', 'Вид крепления, вместимость и нагрузка показываются в характеристиках карточки.', 'Публикуйте товар после проверки карточки и фотографий.']])

<div class="form-grid">
    <div class="field field--wide"><label for="name">Название товара</label><input id="name" name="name" type="text" value="{{ old('name', $product->name ?? '') }}" required><p class="field__hint">Показывается в заголовке карточки и в списках каталога.</p>@error('name')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field field--wide"><label for="slug">Адрес страницы</label><input id="slug" name="slug" type="text" value="{{ old('slug', $product->slug ?? '') }}" placeholder="Заполнится автоматически"><p class="field__hint">Часть ссылки на карточку товара.</p>@error('slug')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field"><label for="price">Цена, ₽</label><input id="price" name="price" type="number" min="0" step="0.01" value="{{ old('price', $product->price ?? '0.00') }}" required><p class="field__hint">Показывается в карточке и в каталоге.</p>@error('price')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field"><label for="stock">Остаток, шт.</label><input id="stock" name="stock" type="number" min="0" step="1" value="{{ old('stock', $product->stock ?? 0) }}" required><p class="field__hint">0 означает «Под заказ».</p>@error('stock')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field"><label for="manufacturer_id">Производитель</label><select id="manufacturer_id" name="manufacturer_id"><option value="">Не выбран</option>@foreach ($bikeRackManufacturers as $manufacturer)<option value="{{ $manufacturer->id }}" @selected($selectedManufacturerId === (string) $manufacturer->id) @disabled(! $manufacturer->is_active && $selectedManufacturerId !== (string) $manufacturer->id)>{{ $manufacturer->name }}{{ $manufacturer->is_active ? '' : ' (скрыт)' }}</option>@endforeach</select><p class="field__hint">Показывается в характеристиках карточки. <a class="text-link" href="{{ route('admin.products.bike-racks.manufacturers.index') }}">Открыть справочник производителей</a></p>@error('manufacturer_id')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field"><label for="country_of_origin">Страна производства</label><input id="country_of_origin" name="country_of_origin" type="text" value="{{ old('country_of_origin', $product->country_of_origin ?? '') }}" maxlength="255"><p class="field__hint">Показывается в характеристиках карточки.</p>@error('country_of_origin')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field field--wide"><label for="product_model">Модель товара</label><input id="product_model" name="product_model" type="text" value="{{ old('product_model', $product->product_model ?? '') }}" maxlength="255"><p class="field__hint">Артикул или модель производителя; показывается в характеристиках карточки.</p>@error('product_model')<p class="field__error">{{ $message }}</p>@enderror</div>

    <fieldset class="field field--wide product-specific-fields"><legend>Характеристики велокрепления</legend><p class="field__hint">Заполненные значения показываются в таблице характеристик на карточке товара.</p><div class="form-grid product-specific-fields__grid">
        <div class="field"><label for="mounting_type">Тип крепления</label><select id="mounting_type" name="mounting_type"><option value="">Не выбран</option>@foreach (['На крышу', 'На фаркоп', 'На заднюю дверь'] as $type)<option value="{{ $type }}" @selected(old('mounting_type', $bikeRack?->mounting_type ?? '') === $type)>{{ $type }}</option>@endforeach</select><p class="field__hint">Место установки крепления на автомобиле.</p>@error('mounting_type')<p class="field__error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="bike_capacity">Вместимость, велосипедов</label><input id="bike_capacity" name="bike_capacity" type="number" min="1" max="10" step="1" value="{{ old('bike_capacity', $bikeRack?->bike_capacity ?? '') }}"><p class="field__hint">Максимальное число перевозимых велосипедов.</p>@error('bike_capacity')<p class="field__error">{{ $message }}</p>@enderror</div>
        <div class="field"><label for="load_capacity_kg">Грузоподъёмность, кг</label><input id="load_capacity_kg" name="load_capacity_kg" type="number" min="0" step="0.1" value="{{ old('load_capacity_kg', $bikeRack?->load_capacity_kg ?? '') }}"><p class="field__hint">Допустимая суммарная нагрузка по данным производителя.</p>@error('load_capacity_kg')<p class="field__error">{{ $message }}</p>@enderror</div>
    </div></fieldset>

    <div class="field field--wide"><label for="description">Описание</label><textarea id="description" name="description" rows="8">{{ old('description', $product->description ?? '') }}</textarea><p class="field__hint">Основной текст внизу карточки товара.</p>@error('description')<p class="field__error">{{ $message }}</p>@enderror</div>
    <div class="field field--wide"><label for="images">Фотографии</label><input id="images" name="images[]" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple><p class="field__hint">Показываются в галерее карточки товара. До 10 файлов за один раз, каждый до 6 МБ.</p>@error('images.*')<p class="field__error">{{ $message }}</p>@enderror</div>
    @if (isset($product) && $product->images->isNotEmpty())<fieldset class="field field--wide image-manager"><legend>Загруженные фотографии</legend><div class="image-manager__grid">@foreach ($product->images as $image)<label class="image-manager__item"><img src="{{ asset($image->path) }}" alt="{{ $image->alt }}"><span><input type="checkbox" name="remove_image_ids[]" value="{{ $image->id }}"> Удалить при сохранении</span></label>@endforeach</div></fieldset>@endif
    <label class="checkbox field--wide"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $product->is_active ?? false))><span>Опубликовать товар на сайте</span><span class="field__hint">Скрытый товар остаётся в админке, но не показывается покупателям.</span></label>
</div>
<div class="form-actions"><button class="button button--primary button--inline" type="submit">Сохранить</button><a class="button button--secondary" href="{{ route('admin.products.bike-racks.index') }}">Отмена</a>@if (isset($product) && $product->is_active)<a class="text-link form-actions__preview" href="{{ route('products.show', $product) }}" target="_blank" rel="noopener">Открыть на сайте ↗</a>@endif</div>
