@csrf @if(isset($vehicleConfiguration)) @method('PUT') @endif
@include('admin.partials.help', ['title' => 'Заполнение конфигурации', 'text' => 'Название должно помогать отличить этот вариант в подборе и таблицах совместимости. Выберите кузов и тип крыши, особенно если от них зависит установка багажника.', 'items' => ['Годы конфигурации по умолчанию берутся из поколения, но их можно сузить.', 'Статус «проверено» ставьте только после сверки с надёжным источником.', 'Примечание используйте для внутренних уточнений, которые не входят в название.']])
<div class="form-grid">
<div class="field field--wide"><label for="display_name">Отображаемое название</label><input id="display_name" name="display_name" value="{{ old('display_name', $vehicleConfiguration->display_name ?? '') }}" placeholder="Кроссовер, интегрированные рейлинги" required>@error('display_name')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="slug">Код / URL</label><input id="slug" name="slug" value="{{ old('slug', $vehicleConfiguration->slug ?? '') }}" placeholder="Заполнится автоматически">@error('slug')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="vehicle_body_style_id">Тип кузова</label><select id="vehicle_body_style_id" name="vehicle_body_style_id"><option value="">Не указан</option>@foreach($vehicleBodyStyles as $style)<option value="{{ $style->id }}" @selected((string)old('vehicle_body_style_id', $vehicleConfiguration->vehicle_body_style_id ?? '') === (string)$style->id)>{{ $style->name }}{{ $style->is_active ? '' : ' (скрыт)' }}</option>@endforeach</select></div>
<div class="field"><label for="vehicle_roof_type_id">Тип крыши</label><select id="vehicle_roof_type_id" name="vehicle_roof_type_id"><option value="">Не указан</option>@foreach($vehicleRoofTypes as $roof)<option value="{{ $roof->id }}" @selected((string)old('vehicle_roof_type_id', $vehicleConfiguration->vehicle_roof_type_id ?? '') === (string)$roof->id)>{{ $roof->name }}{{ $roof->is_active ? '' : ' (скрыт)' }}</option>@endforeach</select></div>
<div class="field"><label for="year_from">Год начала</label><input id="year_from" name="year_from" type="number" min="1885" max="2200" value="{{ old('year_from', $vehicleConfiguration->year_from ?? $vehicleGeneration->year_from) }}">@error('year_from')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="year_to">Год окончания</label><input id="year_to" name="year_to" type="number" min="1885" max="2200" value="{{ old('year_to', $vehicleConfiguration->year_to ?? $vehicleGeneration->year_to) }}">@error('year_to')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="doors_count">Количество дверей</label><input id="doors_count" name="doors_count" type="number" min="1" max="9" value="{{ old('doors_count', $vehicleConfiguration->doors_count ?? '') }}"></div>
<div class="field"><label for="sort_order">Порядок</label><input id="sort_order" name="sort_order" type="number" min="0" value="{{ old('sort_order', $vehicleConfiguration->sort_order ?? $nextSortOrder ?? 0) }}" required></div>
<div class="field"><label for="verification_status">Проверка</label><select id="verification_status" name="verification_status">@foreach(App\Models\VehicleConfiguration::VERIFICATION_STATUSES as $status)<option value="{{ $status }}" @selected(old('verification_status', $vehicleConfiguration->verification_status ?? 'draft') === $status)>{{ $status }}</option>@endforeach</select></div>
<div class="field field--wide"><label for="notes">Примечание</label><textarea id="notes" name="notes" rows="4">{{ old('notes', $vehicleConfiguration->notes ?? '') }}</textarea></div>
<label class="checkbox field--wide"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $vehicleConfiguration->is_active ?? true))><span>Конфигурация активна</span></label>
</div>
<div class="form-actions"><button class="button button--primary button--inline">Сохранить</button><a class="button button--secondary" href="{{ route('admin.vehicles.vehicle-configurations.index', [$vehicleMake, $vehicleModel, $vehicleGeneration]) }}">Отмена</a></div>
