@extends('layouts.admin')
@section('title', 'Проверка совместимости')
@section('body')
<div class="admin-shell">@include('admin.partials.header')<main class="admin-content admin-content--wide">@include('admin.partials.flash')
<div class="page-heading"><div><p class="eyebrow">Совместимость</p><h1>Проверка с объяснением</h1><p class="admin-content__lead">Для автобокса можно выбрать конкретный багажник или оставить поле пустым, чтобы проверить все подходящие системы автомобиля.</p></div><a class="button button--secondary button--inline" href="{{ route('admin.compatibility-overrides.index') }}">Ручные исключения</a></div>
@include('admin.partials.help', ['id' => 'compatibility-preview-help-title', 'title' => 'Как пользоваться проверкой', 'text' => 'Выберите автомобиль и проверяемый товар. Для багажника система ищет прямую связь через активную группу применяемости. Автобоксы имеют универсальную совместимость и не требуют дополнительной проверки.', 'items' => ['Базовый багажник для проверки автобокса не требуется.', '«Недостаточно данных» относится к товарам, для которых предусмотрены обязательные технические параметры.', 'Если найдено активное ручное исключение, оно заменяет автоматический результат для применимых стратегий.']])
<form class="admin-form" method="GET"><div class="form-grid">
<div class="field field--wide"><label for="vehicle_configuration_id">Автомобиль</label><select id="vehicle_configuration_id" name="vehicle_configuration_id" data-searchable-select required><option value="">Выберите конфигурацию</option>@foreach($vehicleConfigurations as $configuration)<option value="{{ $configuration->id }}" @selected((string)request('vehicle_configuration_id') === (string)$configuration->id)>{{ $configuration->generation->vehicleModel->make->name }} {{ $configuration->generation->vehicleModel->name }} · {{ $configuration->generation->display_name }} · {{ $configuration->display_name }}</option>@endforeach</select></div>
<div class="field field--wide"><label for="product_id">Проверяемый товар</label><select id="product_id" name="product_id" data-searchable-select required><option value="">Выберите товар</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected((string)request('product_id') === (string)$product->id)>{{ $product->name }} · {{ $product->roofRack ? 'багажник' : 'автобокс' }}</option>@endforeach</select></div>
<div class="field field--wide"><label for="base_product_id">Конкретный базовый багажник</label><select id="base_product_id" name="base_product_id" data-searchable-select><option value="">Определить автоматически</option>@foreach($baseProducts as $product)<option value="{{ $product->id }}" @selected((string)request('base_product_id') === (string)$product->id)>{{ $product->name }}</option>@endforeach</select></div>
</div><div class="form-actions"><button class="button button--primary button--inline">Проверить</button></div></form>
@if($result)<section><h2>Результат: {{ $result->statusLabel() }}</h2><p>{{ $result->statusExplanation() }}</p>@if($result->matchedBaseProductId)<p>Подходящий багажник: {{ $baseProducts->firstWhere('id', $result->matchedBaseProductId)?->name }}</p>@endif @if($result->appliedOverrideId)<p><strong>Применено ручное исключение #{{ $result->appliedOverrideId }}</strong></p>@endif<h3>Объяснение проверки</h3><ul>@foreach($result->reasons as $reason)<li>{{ $reason }}</li>@endforeach</ul>@if($result->missingData)<h3>Нужно заполнить</h3><ul>@foreach($result->missingData as $item)<li>{{ $item }}</li>@endforeach</ul>@endif</section>@endif
</main></div>
@once @push('scripts')<script src="{{ asset('js/searchable-select.js') }}" defer></script>@endpush @endonce
@endsection
