<?php

// Коллекции чехлов
$covers = [
	[
		'id' => '1',
		'name' => 'CAYMAN',
		'img' => '<<img class="img good__img" src="/content/covers/img/Cayman_Black_Alkantara_Face.jpg" alt="Чехлы Cayman">',
	],
	[
		'id' => '2',
		'name' => 'Орегон',
		'img' => '',
	],
	[
		'id' => '3',
		'name' => 'Тренд',
		'img' => '',
	],
];

$cayman = [
	[
		'id' => '1',
		'name' => 'CAYMAN черный-белый, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_White_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_White_Front.jpg">',
		'price' => '5000 рублей',
	],
	[
		'id' => '2',
		'name' => 'CAYMAN черный-красный, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_Red_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_Red_Front.jpg">',
		'price' => '5000 рублей',
	],
	[
		'id' => '3',
		'name' => 'CAYMAN черный-серый, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_Gray_Front.jpg">',
		'price' => '5000 рублей',
	],
	[
		'id' => '4',
		'name' => 'CAYMAN черный-синий, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_Blue_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_Blue_Front.jpg">',
		'price' => '5000 рублей',
	],
	[
		'id' => '5',
		'name' => 'CAYMAN черный, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_Front.jpg">',
		'price' => '5000 рублей',
	],
	[
		'id' => '6',
		'name' => 'CAYMAN черный, экокожа-алькантара',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Cayman_Black_Alkantara_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Cayman_Black_Alkantara_Front.jpg">',
		'price' => '5000 рублей',
	],
];

$oregonromb = [
	[
		'id' => '1',
		'name' => ' Орегон Ромб черный-оранжевый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа  - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Romb_Black_Orange_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Romb_Black_Orange_Front.jpg">',
		'price' => '4800 рублей',
	],
	[
		'id' => '2',
		'name' => 'Орегон Ромб черный-серый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центр альная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Romb_Bla ck_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Romb_Black_Gray_Front.jpg">',
		'price' => '4800 рублей',
	],
	[
		'id' => '3',
		'name' => 'Орегон Ромб черный, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Romb_Bla ck_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oreg on_Romb_Black_Front.jpg">',
		'price' => '4800 рублей',
	],
];

$oregonmodel = [
	[
		'id' => '1',
		'name' => 'Орегон Модельные черный Алькантара, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'desc3' => 'Вариант 3: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Alkantara_Black_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Alkantara_Black_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '2',
		'name' => 'Орегон Модельные черный Жаккард, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центр альная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img cla ss="img product__img" src="/content/covers/img/Oregon_Model_Jakkard_Black_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Jakkard_Black_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '3',
		'name' => 'Орегон Модельные черный-серый Алькантара, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Al kantara_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Alkantara_Black_Gray_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '4',
		'name' => 'Орегон Модельные черный-серый Жаккард, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Jakkard_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Jakkard_Black_Gray_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '5',
		'name' => 'Орегон Модельные черный, экокожа',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Black_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Black_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '6',
		'name' => 'Орегон Модельные черный-серый, экокожа',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Black_Gray_Front.jpg">',
		'price' => '4500 рублей',
	],
	[
		'id' => '7',
		'name' => 'Орегон Модельные черный-синий, экокожа',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Model_Black_Blue_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Model_Black_Blue_Front.jpg">',
		'price' => '4500 рублей',
	],
];

$oregonuniversal = [
	[
		'id' => '1',
		'name' => 'Орегон Универсальный черный-бежевый, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'desc3' => 'Вариант 3: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Universal_Black_Beige_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Universal_Black_Beige_Front.jpg">',
		'price' => '3100 рублей',
	],
	[
		'id' => '2',
		'name' => 'Орегон Универсальный черный-белый, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'desc3' => 'Вариант 3: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Universal_Black_White_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Universal_Black_White_Front.jpg">',
		'price' => '3100 рублей',
	],
	[
		'id' => '3',
		'name' => 'Орегон Универсальный черный-оранжевый, экокожа',
		'desc1' => 'Вариант 1: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'desc2' => 'Вариант 2: Экокожа - боковые части, Алькантара - центральная часть',
		'desc3' => 'Вариант 3: Экокожа - боковые части, Жаккард - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Oregon_Universal_Black_Orange_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Oregon_Universal_Black_Orange_Front.jpg">',
		'price' => '3100 рублей',
	],
];

$trendromb = [
	[
		'id' => '1',
		'name' => 'Тренд "Двойной ромб", черный-белый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Black_White_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Black_White_Front.jpg">',
		'price' => '5500 рублей',
	],
	[
		'id' => '2',
		'name' => 'Тренд "Двойной ромб", черный-синий, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Black_Blue_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Black_Blue_Front.jpg">',
		'price' => '5500 рублей',
	],
	[
		'id' => '3',
		'name' => 'Тренд "Двойной ромб", черный, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Black_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Black_Front.jpg">',
		'price' => '5500 рублей',
	],
	[
		'id' => '4',
		'name' => 'Тренд "Двойной ромб", черный-серый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Black_Gray_Front.jpg">',
		'price' => '5500 рублей',
	],
	[
		'id' => '5',
		'name' => 'Тренд "Двойной ромб", черный-красный, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Black_Red_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Black_Red_Front.jpg">',
		'price' => '5500 рублей',
	],
	[
		'id' => '6',
		'name' => 'Тренд "Двойной ромб", шоколадный, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Romb_Choko_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Romb_Choko_Front.jpg">',
		'price' => '5500 рублей',
	],
];

$trend = [
	[
		'id' => '1',
		'name' => 'Тренд, черный-серая алькантара, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Black_Gray_Alk_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Black_Gray_Alk_Front.jpg">',
		'price' => '5600 рублей',
	],
	[
		'id' => '2',
		'name' => 'Тренд, черный-белый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Black_White_Face.jpg"',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Black_White_Front.jpg">',
		'price' => '5600 рублей',
	],
	[
		'id' => '3',
		'name' => 'Тренд, черный-паприка, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Black_Paprika_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Black_Paprika_Front.jpg">',
		'price' => '5600 рублей',
	],
	[
		'id' => '4',
		'name' => 'Тренд, черный-серый, экокожа',
		'desc1' => 'Используемые материалы: Экокожа - боковые части, Перфорированная экокожа - центральная часть',
		'img1' => '<img class="img product__img" src="/content/covers/img/Trend_Black_Gray_Face.jpg">',
		'img2' => '<img class="img product__img product__img--small" src="/content/covers/img/Trend_Black_Gray_Front.jpg">',
		'price' => '5600 рублей',
	],
];
