@csrf @if(isset($compatibilityOverride)) @method('PUT') @endif
@php($override = $compatibilityOverride ?? null)
<div class="form-grid">
<div class="field field--wide"><label for="vehicle_configuration_id">Автомобиль</label><select id="vehicle_configuration_id" name="vehicle_configuration_id" data-searchable-select><option value="">Любой автомобиль</option>@foreach($vehicleConfigurations as $configuration)<option value="{{ $configuration->id }}" @selected((string)old('vehicle_configuration_id', $override?->vehicle_configuration_id ?? '') === (string)$configuration->id)>{{ $configuration->generation->vehicleModel->make->name }} {{ $configuration->generation->vehicleModel->name }} · {{ $configuration->generation->display_name }} · {{ $configuration->display_name }}</option>@endforeach</select></div>
<div class="field"><label for="fitment_id">Группа применяемости</label><select id="fitment_id" name="fitment_id"><option value="">Любая группа</option>@foreach($fitments as $fitment)<option value="{{ $fitment->id }}" @selected((string)old('fitment_id', $override?->fitment_id ?? '') === (string)$fitment->id)>{{ $fitment->code }} · {{ $fitment->name }}</option>@endforeach</select></div>
<div class="field"><label for="priority">Приоритет</label><input id="priority" name="priority" type="number" value="{{ old('priority', $override?->priority ?? 0) }}" required></div>
<div class="field field--wide"><label for="base_product_id">Базовый багажник</label><select id="base_product_id" name="base_product_id" data-searchable-select required><option value="">Выберите товар</option>@foreach($baseProducts as $product)<option value="{{ $product->id }}" @selected((string)old('base_product_id', $override?->base_product_id ?? '') === (string)$product->id)>{{ $product->name }}</option>@endforeach</select>@error('base_product_id')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field field--wide"><label for="accessory_product_id">Аксессуар</label><select id="accessory_product_id" name="accessory_product_id" data-searchable-select><option value="">Нет — исключение прямой применяемости багажника</option>@foreach($accessoryProducts as $product)<option value="{{ $product->id }}" @selected((string)old('accessory_product_id', $override?->accessory_product_id ?? '') === (string)$product->id)>{{ $product->name }}</option>@endforeach</select></div>
<div class="field"><label for="status">Принудительный результат</label><select id="status" name="status"><option value="compatible" @selected(old('status', $override?->status ?? '') === 'compatible')>Совместимо</option><option value="incompatible" @selected(old('status', $override?->status ?? '') === 'incompatible')>Несовместимо</option></select></div>
<div class="field"><label for="source">Источник</label><input id="source" name="source" value="{{ old('source', $override?->source ?? '') }}" placeholder="Производитель, инструкция, проверка"></div>
<div class="field field--wide"><label for="reason">Причина</label><textarea id="reason" name="reason" rows="5" required>{{ old('reason', $override?->reason ?? '') }}</textarea>@error('reason')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="valid_from">Действует с</label><input id="valid_from" name="valid_from" type="datetime-local" value="{{ old('valid_from', $override?->valid_from?->format('Y-m-d\TH:i') ?? '') }}"></div>
<div class="field"><label for="valid_to">Действует до</label><input id="valid_to" name="valid_to" type="datetime-local" value="{{ old('valid_to', $override?->valid_to?->format('Y-m-d\TH:i') ?? '') }}"></div>
<label class="checkbox field--wide"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $override?->is_active ?? true))><span>Исключение активно</span></label>
</div>
<div class="form-actions"><button class="button button--primary button--inline">Сохранить</button><a class="button button--secondary" href="{{ route('admin.compatibility-overrides.index') }}">Отмена</a></div>
@once @push('scripts')<script src="{{ asset('js/searchable-select.js') }}" defer></script>@endpush @endonce
