@extends('layouts.admin')
@section('title', 'Исключения совместимости')
@section('body')
<div class="admin-shell">@include('admin.partials.header')<main class="admin-content admin-content--wide">@include('admin.partials.flash')
<div class="page-heading"><div><p class="eyebrow">Совместимость</p><h1>Ручные исключения</h1><p class="admin-content__lead">Исключения имеют приоритет над автоматическими техническими правилами.</p></div><a class="button button--primary button--inline" href="{{ route('admin.compatibility-overrides.create') }}">Добавить исключение</a></div>
<nav class="admin-shortcuts" aria-label="Инструменты совместимости"><a class="admin-shortcuts__link" href="{{ route('admin.compatibility.quality') }}">Качество применяемости</a><a class="admin-shortcuts__link" href="{{ route('admin.compatibility.preview') }}">Проверить совместимость с объяснением</a><a class="admin-shortcuts__link" href="{{ route('admin.fitments.index') }}">Группы применяемости</a></nav>
@include('admin.partials.help', ['id' => 'overrides-help-title', 'title' => 'Когда нужны ручные исключения', 'text' => 'Используйте исключение, когда подтверждённый производителем или реальной установкой результат отличается от автоматического расчёта. Исключение принудительно задаёт «Совместимо» или «Несовместимо» для выбранного багажника и, при необходимости, конкретного автобокса, автомобиля или группы.', 'items' => ['Не используйте исключения вместо заполнения обычных групп и монтажных размеров.', 'Всегда указывайте понятную причину и источник, чтобы решение можно было проверить позже.', 'Отключение или удаление исключения возвращает действие автоматических правил.']])
<p class="form-description">Фильтр ниже показывает исключения только с выбранным принудительным результатом. Он не фильтрует по активности, автомобилю или товару.</p>
<form class="toolbar"><select name="status"><option value="">Все результаты</option><option value="compatible" @selected(request('status') === 'compatible')>Совместимо</option><option value="incompatible" @selected(request('status') === 'incompatible')>Несовместимо</option></select><select name="quality"><option value="">Все записи</option><option value="conflicts" @selected(request('quality') === 'conflicts')>Только конфликты</option></select><button class="button button--secondary">Применить</button></form>
<div class="table-wrap"><table class="admin-table"><thead><tr><th>Контекст</th><th>Базовый товар</th><th>Аксессуар</th><th>Результат</th><th>Причина</th><th>Статус</th><th></th></tr></thead><tbody>
@forelse($overrides as $override)<tr><td>@if($override->vehicleConfiguration){{ $override->vehicleConfiguration->generation->vehicleModel->make->name }} {{ $override->vehicleConfiguration->generation->vehicleModel->name }}<br><small>{{ $override->vehicleConfiguration->display_name }}</small>@elseif($override->fitment){{ $override->fitment->code }}@elseВсе автомобили@endif</td><td>{{ $override->baseProduct->name }}</td><td>{{ $override->accessoryProduct?->name ?? 'Прямая применяемость' }}</td><td><strong>{{ $override->status }}</strong></td><td>{{ str($override->reason)->limit(100) }}</td><td>{{ $override->is_active ? 'Активно' : 'Отключено' }}</td><td><a class="text-link" href="{{ route('admin.compatibility-overrides.edit', $override) }}">Изменить</a></td></tr>@empty<tr><td colspan="7" class="empty-state">Исключения не найдены.</td></tr>@endforelse
</tbody></table></div>@include('admin.partials.pagination', ['paginator' => $overrides])
</main></div>
@endsection
