@csrf @if(isset($fitment)) @method('PUT') @endif
@php($selectedProducts = array_map('intval', old('product_ids', isset($fitment) ? $fitment->products->pluck('id')->all() : [])))
<div class="form-grid">
<div class="field field--wide"><label for="name">Название</label><input id="name" name="name" value="{{ old('name', $fitment->name ?? '') }}" required>@error('name')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="code">Стабильный код</label><input id="code" name="code" value="{{ old('code', $fitment->code ?? '') }}" placeholder="LUX-RAILS-120"><p class="field__hint">Латиница, цифры и дефис. После использования код лучше не менять.</p>@error('code')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field"><label for="roof_rack_manufacturer_id">Производитель системы</label><select id="roof_rack_manufacturer_id" name="roof_rack_manufacturer_id"><option value="">Не указан</option>@foreach($manufacturers as $manufacturer)<option value="{{ $manufacturer->id }}" @selected((string)old('roof_rack_manufacturer_id', $fitment->roof_rack_manufacturer_id ?? '') === (string)$manufacturer->id)>{{ $manufacturer->name }}</option>@endforeach</select></div>
<div class="field"><label for="verification_status">Статус проверки</label><select id="verification_status" name="verification_status">@foreach(App\Models\Fitment::VERIFICATION_STATUSES as $status)<option value="{{ $status }}" @selected(old('verification_status', $fitment->verification_status ?? 'draft') === $status)>{{ App\Models\Fitment::verificationStatusLabel($status) }}</option>@endforeach</select></div>
<div class="field field--wide"><label for="product_ids">Багажники в группе применяемости</label><select id="product_ids" name="product_ids[]" multiple size="10" data-searchable-select>@foreach($roofRackProducts as $product)<option value="{{ $product->id }}" @selected(in_array($product->id, $selectedProducts, true))>{{ $product->name }}{{ $product->roofRack?->manufacturer?->name ? ' · '.$product->roofRack->manufacturer->name : '' }}{{ $product->is_active ? '' : ' (скрыт)' }}</option>@endforeach</select><p class="field__hint">Автомобили настраиваются отдельно, поэтому карточка группы остаётся компактной.</p>@error('product_ids.*')<p class="field__error">{{ $message }}</p>@enderror</div>
<div class="field field--wide"><label for="notes">Примечание</label><textarea id="notes" name="notes" rows="5">{{ old('notes', $fitment->notes ?? '') }}</textarea></div>
<label class="checkbox field--wide"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $fitment->is_active ?? true))><span>Группа применяемости активна</span></label>
</div>
<div class="form-actions"><button class="button button--primary button--inline">Сохранить</button><a class="button button--secondary" href="{{ route('admin.fitments.index') }}">Отмена</a>@if(isset($fitment))<a class="text-link" href="{{ route('admin.fitments.configurations', $fitment) }}">Автомобили ({{ $fitment->configurations_count }})</a><a class="text-link" href="{{ route('admin.fitments.preview', $fitment) }}">Предпросмотр</a>@endif</div>
@once @push('scripts')<script src="{{ asset('js/searchable-select.js') }}" defer></script>@endpush @endonce
