@extends('layouts.admin')
@section('title', 'Автомобили '.$fitment->code)
@section('body')
<div class="admin-shell">@include('admin.partials.header')<main class="admin-content admin-content--wide">@include('admin.partials.flash')
<nav class="admin-breadcrumbs"><a href="{{ route('admin.fitments.index') }}">Группы применяемости</a><span>/</span><a href="{{ route('admin.fitments.edit', $fitment) }}">{{ $fitment->code }}</a><span>/</span><span>Автомобили</span></nav>
<div class="page-heading"><div><p class="eyebrow">Массовая применяемость</p><h1>{{ $fitment->name }}</h1><p class="admin-content__lead">Выберите до 100 показанных конфигураций и добавьте или удалите их одной операцией.</p></div><a class="button button--secondary button--inline" href="{{ route('admin.fitments.preview', $fitment) }}">Предпросмотр</a></div>
<form class="toolbar toolbar--fitment-configurations" method="GET">
<div class="toolbar__filter-row">
<select name="make_id" onchange="this.form.submit()"><option value="">Все марки</option>@foreach($vehicleMakes as $make)<option value="{{ $make->id }}" @selected((string)request('make_id') === (string)$make->id)>{{ $make->name }}</option>@endforeach</select>
<select name="model_id" onchange="this.form.submit()"><option value="">Все модели</option>@foreach($vehicleModels as $model)<option value="{{ $model->id }}" @selected((string)request('model_id') === (string)$model->id)>{{ $model->name }}</option>@endforeach</select>
<select name="generation_id"><option value="">Все поколения</option>@foreach($vehicleGenerations as $generation)<option value="{{ $generation->id }}" @selected((string)request('generation_id') === (string)$generation->id)>{{ $generation->display_name }}</option>@endforeach</select>
<select name="body_style_id"><option value="">Все кузова</option>@foreach($vehicleBodyStyles as $style)<option value="{{ $style->id }}" @selected((string)request('body_style_id') === (string)$style->id)>{{ $style->name }}</option>@endforeach</select>
<select name="roof_type_id"><option value="">Все крыши</option>@foreach($vehicleRoofTypes as $roof)<option value="{{ $roof->id }}" @selected((string)request('roof_type_id') === (string)$roof->id)>{{ $roof->name }}</option>@endforeach</select>
</div>
<div class="toolbar__search-row">
<input type="search" name="search" value="{{ request('search') }}" placeholder="Поиск по названию конфигурации" aria-label="Поиск по названию конфигурации"><button class="button button--secondary">Применить</button>
</div>
</form>
<form method="POST" action="{{ route('admin.fitments.configurations.update', $fitment) }}">@csrf
<div class="form-actions"><button class="button button--primary button--inline" name="action" value="add">Добавить выбранные</button><button class="button button--secondary button--inline" name="action" value="save_parameters">Сохранить параметры</button><button class="button button--secondary button--inline" name="action" value="remove">Удалить выбранные</button><span>Всего в группе: {{ count($selectedIds) }}</span></div>
<div class="table-wrap"><table class="admin-table"><thead><tr><th><input type="checkbox" onclick="document.querySelectorAll('[data-configuration-checkbox]').forEach(checkbox => checkbox.checked = this.checked)" aria-label="Выбрать все"></th><th>Марка / модель</th><th>Поколение / конфигурация</th><th>Кузов / крыша</th><th>Дуги, мм</th><th>Нагрузка, кг</th><th>Сейчас</th></tr></thead><tbody>
@forelse($configurations as $configuration)@php($selected = $selectedConfigurations->get($configuration->id))<tr><td><input data-configuration-checkbox type="checkbox" name="configuration_ids[]" value="{{ $configuration->id }}"></td><td>{{ $configuration->generation->vehicleModel->make->name }} · {{ $configuration->generation->vehicleModel->name }}</td><td>{{ $configuration->generation->display_name }}<br><small>{{ $configuration->display_name }}</small></td><td>{{ $configuration->bodyStyle?->name ?? '—' }}<br><small>{{ $configuration->roofType?->name ?? '—' }}</small></td><td><input aria-label="Минимальное расстояние" name="parameters[{{ $configuration->id }}][crossbar_spacing_min_mm]" type="number" min="1" placeholder="от" value="{{ old('parameters.'.$configuration->id.'.crossbar_spacing_min_mm', $selected?->pivot?->crossbar_spacing_min_mm) }}" style="width:75px"> <input aria-label="Максимальное расстояние" name="parameters[{{ $configuration->id }}][crossbar_spacing_max_mm]" type="number" min="1" placeholder="до" value="{{ old('parameters.'.$configuration->id.'.crossbar_spacing_max_mm', $selected?->pivot?->crossbar_spacing_max_mm) }}" style="width:75px"></td><td><input aria-label="Максимальная динамическая нагрузка" name="parameters[{{ $configuration->id }}][max_dynamic_load_kg]" type="number" min="0" step="0.1" value="{{ old('parameters.'.$configuration->id.'.max_dynamic_load_kg', $selected?->pivot?->max_dynamic_load_kg) }}" style="width:85px"></td><td>{{ $selected ? 'Добавлена' : 'Не добавлена' }}</td></tr>@empty<tr><td colspan="7" class="empty-state">Конфигурации не найдены.</td></tr>@endforelse
</tbody></table></div></form>@include('admin.partials.pagination', ['paginator' => $configurations])
</main></div>
@endsection
