@extends('layouts.admin')
@section('title', 'Группы применяемости')
@section('body')
<div class="admin-shell">@include('admin.partials.header')<main class="admin-content admin-content--wide">@include('admin.partials.flash')
<div class="page-heading"><div><p class="eyebrow">Совместимость</p><h1>Группы применяемости</h1><p class="admin-content__lead">Группы применяемости монтажных систем к конфигурациям автомобилей.</p></div><a class="button button--primary button--inline" href="{{ route('admin.fitments.create') }}">Добавить группу</a></div>
<nav class="admin-shortcuts" aria-label="Инструменты совместимости"><a class="admin-shortcuts__link" href="{{ route('admin.compatibility.quality') }}">Качество применяемости</a><a class="admin-shortcuts__link" href="{{ route('admin.compatibility.preview') }}">Проверить совместимость</a><a class="admin-shortcuts__link" href="{{ route('admin.compatibility-overrides.index') }}">Ручные исключения</a></nav>
@include('admin.partials.help', ['id' => 'fitments-help-title', 'title' => 'Как работают группы применяемости', 'text' => 'Группа связывает один или несколько однотипных багажников с автомобилями, на которые они устанавливаются. Все товары группы считаются подходящими ко всем добавленным в неё конфигурациям автомобилей — это позволяет один раз настроить применяемость для целой монтажной системы.', 'items' => ['Создайте группу и добавьте в неё багажники с одинаковой применяемостью.', 'Откройте группу, настройте автомобили и при необходимости укажите монтажные параметры.', 'Перед публикацией проверьте итоговый список через предпросмотр.']])
<p class="form-description">Поиск ниже фильтрует список только по названию или стабильному коду группы. Для поиска автомобиля откройте нужную группу и нажмите «Настроить автомобили».</p>
<form class="toolbar" method="GET"><input name="search" value="{{ request('search') }}" placeholder="Код или название"><select name="verification_status"><option value="">Статус проверки: все</option>@foreach (App\Models\Fitment::VERIFICATION_STATUS_LABELS as $status => $label)<option value="{{ $status }}" @selected(request('verification_status') === $status)>{{ $label }}</option>@endforeach</select><select name="quality"><option value="">Все группы</option><option value="no_products" @selected(request('quality') === 'no_products')>Без товаров</option><option value="no_configurations" @selected(request('quality') === 'no_configurations')>Без автомобилей</option></select><button class="button button--secondary">Применить</button></form>
<div class="table-wrap"><table class="admin-table"><thead><tr><th>Группа</th><th>Производитель</th><th>Автомобили</th><th>Товары</th><th>Статус</th><th></th></tr></thead><tbody>
@forelse($fitments as $fitment)<tr><td><strong>{{ $fitment->name }}</strong><br><code>{{ $fitment->code }}</code></td><td>{{ $fitment->manufacturer?->name ?? '—' }}</td><td><a class="text-link" href="{{ route('admin.fitments.configurations', $fitment) }}">{{ $fitment->configurations_count }}</a></td><td>{{ $fitment->products_count }}</td><td>{{ $fitment->is_active ? 'Активна' : 'Скрыта' }}</td><td><div class="row-actions"><a class="text-link" href="{{ route('admin.fitments.edit', $fitment) }}">Изменить</a><form method="POST" action="{{ route('admin.fitments.copy', $fitment) }}">@csrf <button class="text-link text-link--button" type="submit">Копировать</button></form></div></td></tr>@empty<tr><td colspan="6" class="empty-state">Группы применяемости не найдены.</td></tr>@endforelse
</tbody></table></div>@include('admin.partials.pagination', ['paginator' => $fitments])
</main></div>
@endsection
