<?php
$expiditions = [
    [
        'id' => 'abcheviniva',
        'name' => 'БАГАЖНИК НА НИВУ ШЕВРОЛЕ',
        'desc1' => 'Корзина экспедиционного сварного багажника',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/cheviniva/cheviniva-1.JPG',
        'img2' => '/content/expiditions/img/cheviniva/cheviniva-2.JPG',
        'img3' => '/content/expiditions/img/cheviniva/cheviniva-3.JPG',
        'img4' => '/content/expiditions/img/cheviniva/cheviniva-4.JPG',
        'price' => '11 000 рублей',
    ],
    [
        'id' => 'absuzukijimmny',
        'name' => 'БАГАЖНИК ДЛЯ SUZUKI JIMNY',
        'img1' => '/content/expiditions/img/jimmy/jimmy-1.jpg',
        'img2' => '/content/expiditions/img/jimmy/jimmy-2.jpg',
        'img3' => '/content/expiditions/img/jimmy/jimmy-3.jpg',
        'img4' => '/content/expiditions/img/jimmy/jimmy-4.jpg',
        'img5' => '/content/expiditions/img/jimmy/jimmy-5.jpg',
        'price' => '11 000 рублей',
    ],
    [
        'id' => 'abrenodaster',
        'name' => 'БАГАЖНИК НА РЕНО ДАСТЕР',
        'desc1' => 'Корзина экспедиционного сварного багажника',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/duster/duster-1.jpg',
        'img2' => '/content/expiditions/img/duster/duster-2.jpg',
        'img3' => '/content/expiditions/img/duster/duster-3.jpg',
        'img4' => '/content/expiditions/img/duster/duster-4.jpg',
        'price' => '11 000 рублей',
    ],
    [
        'id' => 'abplatforma',
        'name' => 'БАГАЖНАЯ ПЛАТФОРМА',
        'desc1' => 'Подходит на любые авто с креплением на рейлинги или поперечины.',
        'img1' => '/content/expiditions/img/platforma/platforma-1.jpg',
        'img2' => '/content/expiditions/img/platforma/platforma-2.jpg',
        'img3' => '/content/expiditions/img/platforma/platforma-3.jpg',
        'img4' => '/content/expiditions/img/platforma/platforma-4.jpg',
        'price' => '7 000 рублей',
    ],
    [
        'id' => 'abkorzina',
        'name' => 'БАГАЖНАЯ КОРЗИНА',
        'desc1' => 'Подходит на любые авто с креплением на рейлинги или поперечины.',
        'img1' => '/content/expiditions/img/korzina/korzina-1.jpg',
        'img2' => '/content/expiditions/img/korzina/korzina-2.jpg',
        'img3' => '/content/expiditions/img/korzina/korzina-3.jpg',
        'img4' => '/content/expiditions/img/korzina/korzina-4.jpg',
        'price' => '7 000 рублей',
    ],
    [
        'id' => 'abexpidition',
        'name' => 'ЭКСПЕДИЦИОННЫЙ БАГАЖНИК',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/universal/universal-1.jpg',
        'img2' => '/content/expiditions/img/universal/universal-2.jpg',
        'img3' => '/content/expiditions/img/universal/universal-3.jpg',
        'price' => '9 000 рублей',
    ],
    [
        'id' => 'abplatforma-vodostok',
        'name' => 'БАГАЖНАЯ ПЛАТФОРМА НА ВОДОСТОКИ',
        'desc1' => 'Предназначена для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/platforma-vodostok/platforma-1.jpg',
        'img2' => '/content/expiditions/img/platforma-vodostok/platforma-2.jpg',
        'price' => '9 000 рублей',
    ],
    [
        'id' => 'abkorzina-universal',
        'name' => 'УНИВЕРСАЛЬНАЯ БАГАЖНАЯ КОРЗИНА',
        'desc1' => 'Предназначена для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/korzina-universal/universal-1.png',
        'img2' => '/content/expiditions/img/korzina-universal/universal-2.jpg',
        'img3' => '/content/expiditions/img/korzina-universal/universal-3.jpg',
        'price' => '9 000 рублей',
    ],
    [
        'id' => 'abniva2121',
        'name' => 'БАГАЖНИК НА НИВУ 2121',
        'desc1' => 'Экспедиционного багажник на 3-х дверную Ниву',
        'desc2' => 'Предназначена для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/niva2121/niva2121-1.jpg',
        'img2' => '/content/expiditions/img/niva2121/niva2121-2.jpg',
        'img3' => '/content/expiditions/img/niva2121/niva2121-3.jpg',
        'price' => '9 000 рублей',
    ],
    [
        'id' => 'abkiasportage',
        'name' => 'БАГАЖНИК НА КИА СПОРТЕЙДЖ',
        'img1' => '/content/expiditions/img/sportage/sportage-1.png',
        'img2' => '/content/expiditions/img/sportage/sportage-2.jpg',
        'img3' => '/content/expiditions/img/sportage/sportage-3.jpg',
        'price' => '10 000 рублей',
    ],
    [
        'id' => 'abniva2131',
        'name' => 'БАГАЖНИК НА НИВУ 2131',
        'desc1' => 'Экспедиционного багажник на 5-х дверную Ниву',
        'desc2' => 'Предназначена для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/niva2131/niva2131-1.jpg',
        'img2' => '/content/expiditions/img/niva2131/niva2131-2.jpg',
        'img3' => '/content/expiditions/img/niva2131/niva2131-3.jpg',
        'img4' => '/content/expiditions/img/niva2131/niva2131-4.jpg',
        'price' => '10 000 рублей',
    ],
    [
        'id' => 'abusilennyi',
        'name' => 'БАГАЖНИК С УСИЛЕННОЙ ПЕРЕДНЕЙ ПЛОЩАДКОЙ',
        'img1' => '/content/expiditions/img/usilennyi/usilennyi-1.jpg',
        'img2' => '/content/expiditions/img/usilennyi/usilennyi-2.jpg',
        'img3' => '/content/expiditions/img/usilennyi/usilennyi-3.jpg',
        'img4' => '/content/expiditions/img/usilennyi/usilennyi-4.jpg',
        'price' => '12 000 рублей',
    ],
    [
        'id' => 'abtoyotaprado',
        'name' => 'БАГАЖНИК ТОЙОТА ПРАДО',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/prado/prado-1.jpg',
        'img2' => '/content/expiditions/img/prado/prado-2.jpg',
        'img3' => '/content/expiditions/img/prado/prado-3.jpg',
        'img4' => '/content/expiditions/img/prado/prado-4.jpg',
        'price' => '12 000 рублей',
    ],
    [
        'id' => 'abpatriot',
        'name' => 'БАГАЖНИК НА УАЗ ПАТРИОТ',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/patriot/patriot-1.JPG',
        'img2' => '/content/expiditions/img/patriot/patriot-2.JPG',
        'img3' => '/content/expiditions/img/patriot/patriot-3.JPG',
        'price' => '12 000 рублей',
    ],
    [
        'id' => 'abxterra',
        'name' => 'БАГАЖНИК NISSAN X-TERRA',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/terra/terra-1.jpg',
        'img2' => '/content/expiditions/img/terra/terra-2.jpg',
        'img3' => '/content/expiditions/img/terra/terra-3.jpg',
        'price' => '12 000 рублей',
    ],
    [
        'id' => 'abmodern',
        'name' => 'БАГАЖНИК МОДЕРН С УСИЛЕННЫМ ДНОМ',
        'img1' => '/content/expiditions/img/modern/modern-1.png',
        'img2' => '/content/expiditions/img/modern/modern-2.png',
        'img3' => '/content/expiditions/img/modern/modern-3.png',
        'price' => '12 000 рублей',
    ],
    [
        'id' => 'ablux-3door',
        'name' => 'БАГАЖНИК ЛЮКС ДЛЯ 3-Х ДВЕРНОЙ НИВЫ',
        'img1' => '/content/expiditions/img/niva-3door/3door-1.jpg',
        'img2' => '/content/expiditions/img/niva-3door/3door-2.jpg',
        'img3' => '/content/expiditions/img/niva-3door/3door-3.jpg',
        'img4' => '/content/expiditions/img/niva-3door/3door-4.jpg',
        'price' => '13 000 рублей',
    ],
    [
        'id' => 'abwallhover',
        'name' => 'БАГАЖНИК НА ГРЕЙТ ВОЛЛ ХОВЕР',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/wall-hover/wall-hover-1.jpg',
        'img2' => '/content/expiditions/img/wall-hover/wall-hover-2.jpg',
        'img3' => '/content/expiditions/img/wall-hover/wall-hover-3.jpg',
        'price' => '14 000 рублей',
    ],
    [
        'id' => 'abuazhunter',
        'name' => 'БАГАЖНИК НА УАЗ ХАНТЕР',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/uaz-hunter/uaz-hunter-1.png',
        'img2' => '/content/expiditions/img/uaz-hunter/uaz-hunter-2.jpg',
        'img3' => '/content/expiditions/img/uaz-hunter/uaz-hunter-3.png',
        'price' => '11 000 рублей',
    ],
    [
        'id' => 'abmodern-duster',
        'name' => 'БАГАЖНИК МОДЕРН + НА ДАСТЕР',
        'img1' => '/content/expiditions/img/modern-duster/modern-duster-1.JPG',
        'img2' => '/content/expiditions/img/modern-duster/modern-duster-2.png',
        'img3' => '/content/expiditions/img/modern-duster/modern-duster-3.JPG',
        'price' => '14 000 рублей',
    ],
    [
        'id' => 'abnina-5door',
        'name' => 'БАГАЖНИК ЛЮКС ДЛЯ 5-ТИ ДВЕРНОЙ НИВЫ',
        'img1' => '/content/expiditions/img/lux-5door/lux-5door-1.jpg',
        'img2' => '/content/expiditions/img/lux-5door/lux-5door-2.jpg',
        'img3' => '/content/expiditions/img/lux-5door/lux-5door-3.jpg',
        'price' => '14 000 рублей',
    ],
    [
        'id' => 'abuaz',
        'name' => 'БАГАЖНИК НА УАЗИК',
        'img1' => '/content/expiditions/img/uaz/uaz-1.jpg',
        'img2' => '/content/expiditions/img/uaz/uaz-2.jpg',
        'img3' => '/content/expiditions/img/uaz/uaz-3.jpg',
        'img4' => '/content/expiditions/img/uaz/uaz-4.jpg',
        'price' => '17 000 рублей',
    ],
    [
        'id' => 'abmodern-lux',
        'name' => 'БАГАЖНИК МОДЕРН ЛЮКС С ОБВЕСОМ',
        'img1' => '/content/expiditions/img/lux-obves/lux-obves-1.jpg',
        'img2' => '/content/expiditions/img/lux-obves/lux-obves-2.jpg',
        'img3' => '/content/expiditions/img/lux-obves/lux-obves-3.jpg',
        'img4' => '/content/expiditions/img/lux-obves/lux-obves-4.jpg',
        'price' => '15 000 рублей',
    ],
    [
        'id' => 'abrendjer',
        'name' => 'БАГАЖНИК НА ФОРД РЕНДЖЕР (ДВОЙНОЙ)',
        'desc1' => 'Корзина экспедиционного сварного багажника ',
        'desc2' => 'Предназначен для перевозки крупногабаритных и тяжелых грузов до 200 кг',
        'img1' => '/content/expiditions/img/ford-ranger/ford-ranger-1.jpg',
        'img2' => '/content/expiditions/img/ford-ranger/ford-ranger-2.jpg',
        'img3' => '/content/expiditions/img/ford-ranger/ford-ranger-3.jpg',
        'price' => '17 000 рублей',
    ],
    [
        'id' => 'abfurgon',
        'name' => 'БАГАЖНИК НА ФУРГОН',
        'img1' => '/content/expiditions/img/furgon/furgon-1.jpg',
        'img2' => '/content/expiditions/img/furgon/furgon-2.jpg',
        'img3' => '/content/expiditions/img/furgon/furgon-3.jpg',
        'img4' => '/content/expiditions/img/furgon/furgon-4.jpg',
        'price' => '17 000 рублей',
    ],
];