<?php
$gallery = [
    [
        'id' => 1,
        'name' => 'Lada Xray',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170303_1_xray.jpg" alt="Lada Xray">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170303_2_xray.jpg" alt="Lada Xray">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170303_3_xray.jpg" alt="Lada Xray">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170303_4_xray.jpg" alt="Lada Xray">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170303_5_xray.jpg" alt="Lada Xray">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170303_6_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 2,
        'name' => 'BMW X5',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170429_1_bmwx5.jpg" alt="BMW X5">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170429_2_bmwx5.jpg" alt="BMW X5">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170429_3_bmwx5.jpg" alt="BMW X5">',
    ],
    [
        'id' => 3,
        'name' => 'Mazda MPV',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170511_1_mpv.jpg" alt="Mazda MPV">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170511_2_mpv.jpg" alt="Mazda MPV">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170511_3_mpv.jpg" alt="Mazda MPV">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170511_4_mpv.jpg" alt="Mazda MPV">',
    ],
    [
        'id' => 4,
        'name' => 'UAZ Patriot',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170513_1_patriot.jpg" alt="UAZ Patriot">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170513_2_patriot.jpg" alt="UAZ Patriot">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170513_3_patriot.jpg" alt="UAZ Patriot">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170513_4_patriot.jpg" alt="UAZ Patriot">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170513_5_patriot.jpg" alt="UAZ Patriot">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170513_6_patriot.jpg" alt="UAZ Patriot">',
        'img7' => '<img class="img good__img" src="/content/gallery/img/20170513_7_patriot.jpg" alt="UAZ Patriot">',
        'img8' => '<img class="img good__img" src="/content/gallery/img/20170513_8_patriot.jpg" alt="UAZ Patriot">',
    ],
    [
        'id' => 5,
        'name' => 'Volkswagen Jetta',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170517_1_jetta.jpg" alt="Volkswagen Jetta">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170517_2_jetta.jpg" alt="Volkswagen Jetta">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170517_3_jetta.jpg" alt="Volkswagen Jetta">',
    ],
    [
        'id' => 6,
        'name' => 'Nissan X-Trail',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170517_1_xtrail.jpg" alt="Nissan X-Trail">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170517_2_xtrail.jpg" alt="Nissan X-Trail">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170517_3_xtrail.jpg" alt="Nissan X-Trail">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170517_4_xtrail.jpg" alt="Nissan X-Trail">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170517_5_xtrail.jpg" alt="Nissan X-Trail">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170517_6_xtrail.jpg" alt="Nissan X-Trail">',
    ],
    [
        'id' => 7,
        'name' => 'Lada 2111',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170525_1_2111.jpg" alt="Lada 2111">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170525_2_2111.jpg" alt="Lada 2111">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170525_3_2111.jpg" alt="Lada 2111">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170525_4_2111.jpg" alt="Lada 2111">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170525_5_2111.jpg" alt="Lada 2111">',
    ],
    [
        'id' => 8,
        'name' => 'Lada Largus',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170525_1_lada.jpg" alt="Lada Largus">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170525_2_lada.jpg" alt="Lada Largus">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170525_3_lada.jpg" alt="Lada Largus">',
    ],
    [
        'id' => 9,
        'name' => 'Ford Focus 2',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170528_1_ford.jpg" alt="Ford Focus 2">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170528_2_ford.jpg" alt="Ford Focus 2">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170528_3_ford.jpg" alt="Ford Focus 2">',
    ],
    [
        'id' => 10,
        'name' => 'Kia Seed',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170602_1_seed.jpg" alt="Kia Seed">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170602_2_seed.jpg" alt="Kia Seed">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170602_3_seed.jpg" alt="Kia Seed">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170602_4_seed.jpg" alt="Kia Seed">',
    ],
    [
        'id' => 11,
        'name' => 'Lada Xray',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170602_1_xray.jpg" alt="Lada Xray">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170602_2_xray.jpg" alt="Lada Xray">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170602_3_xray.jpg" alt="Lada Xray">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170602_4_xray.jpg" alt="Lada Xray">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170602_5_xray.jpg" alt="Lada Xray">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170602_6_xray.jpg" alt="Lada Xray">',
        'img7' => '<img class="img good__img" src="/content/gallery/img/20170602_7_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 12,
        'name' => 'Niva Chevrolet',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170611_1_niva.jpg" alt="Niva Chevrolet">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170611_2_niva.jpg" alt="Niva Chevrolet">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170611_3_niva.jpg" alt="Niva Chevrolet">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170611_4_niva.jpg" alt="Niva Chevrolet">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170611_5_niva.jpg" alt="Niva Chevrolet">',
    ],
    [
        'id' => 13,
        'name' => 'Kia Rio',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170616_1_rio.jpg" alt="Kia Rio">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170616_2_rio.jpg" alt="Kia Rio">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170616_3_rio.jpg" alt="Kia Rio">',
    ],
    [
        'id' => 14,
        'name' => 'Lada 2107',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170617_1_2107.jpg" alt="Lada 2107">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170617_2_2107.jpg" alt="Lada 2107">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170617_3_2107.jpg" alt="Lada 2107">',
    ],
    [
        'id' => 15,
        'name' => 'Mitsubisi Lancer',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170617_1_lancer.jpg" alt="Mitsubisi Lancer">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170617_2_lancer.jpg" alt="Mitsubisi Lancer">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170617_3_lancer.jpg" alt="Mitsubisi Lancer">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170617_4_lancer.jpg" alt="Mitsubisi Lancer">',
    ],
    [
        'id' => 16,
        'name' => 'Subaru Outback',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170617_1_outback.jpg" alt="Subaru Outback">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170617_2_outback.jpg" alt="Subaru Outback">',
    ],
    [
        'id' => 17,
        'name' => 'Lada 2111',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170621_1_2111.jpg" alt="Lada 2111">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170621_2_2111.jpg" alt="Lada 2111">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170621_3_2111.jpg" alt="Lada 2111">',
    ],
    [
        'id' => 18,
        'name' => 'Volkswagen Polo',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170621_1_polo.jpg" alt="Volkswagen Polo">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170621_2_polo.jpg" alt="Volkswagen Polo">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170621_3_polo.jpg" alt="Volkswagen Polo">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170621_4_polo.jpg" alt="Volkswagen Polo">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170621_5_polo.jpg" alt="Volkswagen Polo">',
    ],
    [
        'id' => 19,
        'name' => 'BMW X5',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170621_1_x5.jpg" alt="BMW X5">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170621_2_x5.jpg" alt="BMW X5">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170621_3_x5.jpg" alt="BMW X5">',
    ],
    [
        'id' => 20,
        'name' => 'Chevrolet Niva',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170623_1_niva.jpg" alt="Chevrolet Niva">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170623_2_niva.jpg" alt="Chevrolet Niva">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170623_3_niva.jpg" alt="Chevrolet Niva">',
    ],
    [
        'id' => 21,
        'name' => 'Lifan X50',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170623_1_x50.jpg" alt="Lifan X50">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170623_2_x50.jpg" alt="Lifan X50">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170623_3_x50.jpg" alt="Lifan X50">',
    ],
    [
        'id' => 22,
        'name' => 'Reno Logan',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170716_1_logan.jpg" alt="Reno Logan">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170716_2_logan.jpg" alt="Reno Logan">',
    ],
    [
        'id' => 23,
        'name' => 'Lada Xray',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170727_1_xray.jpg" alt="Lada Xray">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170727_2_xray.jpg" alt="Lada Xray">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170727_3_xray.jpg" alt="Lada Xray">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170727_4_xray.jpg" alt="Lada Xray">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170727_5_xray.jpg" alt="Lada Xray">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170727_6_xray.jpg" alt="Lada Xray">',
        'img7' => '<img class="img good__img" src="/content/gallery/img/20170727_7_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 24,
        'name' => 'Skoda Rapid',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170728_1_rapid.jpg" alt="Skoda Rapid">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170728_2_rapid.jpg" alt="Skoda Rapid">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170728_3_rapid.jpg" alt="Skoda Rapid">',
    ],
    [
        'id' => 25,
        'name' => 'Lada Xray',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170730_1_xray.jpg" alt="Lada Xray">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170730_2_xray.jpg" alt="Lada Xray">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170730_3_xray.jpg" alt="Lada Xray">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170730_4_xray.jpg" alt="Lada Xray">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170730_5_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 26,
        'name' => 'Hyundai Creta',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170801_1_creta.jpg" alt="Hyundai Creta">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170801_2_creta.jpg" alt="Hyundai Creta">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170801_3_creta.jpg" alt="Hyundai Creta">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170801_4_creta.jpg" alt="Hyundai Creta">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170801_5_creta.jpg" alt="Hyundai Creta">',
        'img6' => '<img class="img good__img" src="/content/gallery/img/20170801_6_creta.jpg" alt="Hyundai Creta">',
    ],
    [
        'id' => 27,
        'name' => 'Toyota Land Cryiser',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170809_1_landcryiser.jpg" alt="Toyota Land Cryiser">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170809_2_landcryiser.jpg" alt="Toyota Land Cryiser">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170809_3_landcryiser.jpg" alt="Toyota Land Cryiser">',
    ],
    [
        'id' => 28,
        'name' => 'Reno Duster',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170810_1_duster.jpg" alt="Reno Duster">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170810_2_duster.jpg" alt="Reno Duster">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170810_3_duster.jpg" alt="Reno Duster">',
    ],
    [
        'id' => 29,
        'name' => 'Reno Sandero',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170820_1_sandero.jpg" alt="Reno Sandero">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170820_2_sandero.jpg" alt="Reno Sandero">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170820_3_sandero.jpg" alt="Reno Sandero">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170820_4_sandero.jpg" alt="Reno Sandero">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170820_5_sandero.jpg" alt="Reno Sandero">',
    ],
    [
        'id' => 30,
        'name' => 'Skoda Ieti',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170826_1_ieti.jpg" alt="Skoda Ieti">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170826_2_ieti.jpg" alt="Skoda Ieti">',
    ],
    [
        'id' => 31,
        'name' => 'Hyundai ix35',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170831_1_ix35.jpg" alt="Hyundai ix35">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170831_2_ix35.jpg" alt="Hyundai ix35">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170831_3_ix35.jpg" alt="Hyundai ix35">',
    ],
    [
        'id' => 32,
        'name' => 'Lada Xray',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170902_1_xray.jpg" alt="Lada Xray">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170902_2_xray.jpg" alt="Lada Xray">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170902_3_xray.jpg" alt="Lada Xray">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170902_4_xray.jpg" alt="Lada Xray">',
        'img5' => '<img class="img good__img" src="/content/gallery/img/20170902_5_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 33,
        'name' => 'Opel Mokka',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20170908_1_mokka.jpg" alt="Opel Mokka">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20170908_2_mokka.jpg" alt="Opel Mokka">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20170908_3_mokka.jpg" alt="Opel Mokka">',
        'img4' => '<img class="img good__img" src="/content/gallery/img/20170908_4_mokka.jpg" alt="Opel Mokka">',
    ],
    [
        'id' => 34,
        'name' => 'Reno Kaptur',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20180208_1_kaptur.jpg" alt="Reno Kaptur">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20180208_2_kaptur.jpg" alt="Reno Kaptur">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20180208_3_kaptur.jpg" alt="Reno Kaptur">',
    ],
    [
        'id' => 35,
        'name' => 'Lada Приора',
        'img1' => '<img class="img good__img" src="/content/gallery/img/20180208_1_priora.jpg" alt="Lada Priora">',
        'img2' => '<img class="img good__img" src="/content/gallery/img/20180208_2_priora.jpg" alt="Lada Priora">',
        'img3' => '<img class="img good__img" src="/content/gallery/img/20180208_3_priora.jpg" alt="Lada Priora">',
    ],
];