<?php
$pages = [
    [
        'id' => '1',
        'pagename' => 'xray0303',
        'name' => 'Lada Xray',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170303_1_xray.jpg"  alt="Lada Xray">',
    ],
    [
        'id' => 2,
        'name' => 'BMW X5',
        'pagename' => 'bmwx5',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170429_1_bmwx5.jpg" alt="BMW X5">',
    ],
    [
        'id' => 3,
        'name' => 'Mazda MPV',
        'pagename' => 'mazdampv',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170511_1_mpv.jpg" alt="Mazda MPV">',
    ],
    [
        'id' => 4,
        'name' => 'UAZ Patriot',
        'pagename' => 'uazpatriot',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170513_1_patriot.jpg" alt="UAZ Patriot">',
    ],
    [
        'id' => 5,
        'name' => 'Volkswagen Jetta',
        'pagename' => 'wvjetta',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170517_1_jetta.jpg" alt="Volkswagen Jetta">',
    ],
    [
        'id' => 6,
        'name' => 'Nissan X-Trail',
        'pagename' => 'xtrail',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170517_1_xtrail.jpg" alt="Nissan X-Trail">',
    ],
    [
        'id' => 7,
        'name' => 'Lada 2111',
        'pagename' => 'lada2111',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170525_1_2111.jpg" alt="Lada 2111">',
    ],
    [
        'id' => 8,
        'name' => 'Lada Largus',
        'pagename' => 'ladalargus',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170525_1_lada.jpg" alt="Lada Largus">',
    ],
    [
        'id' => 9,
        'name' => 'Ford Focus 2',
        'pagename' => 'focus2',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170528_1_ford.jpg" alt="Ford Focus 2">',
    ],
    [
        'id' => 10,
        'name' => 'Kia Seed',
        'pagename' => 'seed',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170602_1_seed.jpg" alt="Kia Seed">',
    ],
    [
        'id' => 11,
        'name' => 'Lada Xray',
        'pagename' => 'xray0602',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170602_1_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 12,
        'name' => 'Niva Chevrolet',
        'pagename' => 'chevrolet',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170611_1_niva.jpg" alt="Niva Chevrolet">',
    ],
    [
        'id' => 13,
        'name' => 'Kia Rio',
        'pagename' => 'kiario',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170616_1_rio.jpg" alt="Kia Rio">',
    ],
    [
        'id' => 14,
        'name' => 'Lada 2107',
        'pagename' => 'lada2107',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170617_1_2107.jpg" alt="Lada 2107">',
    ],
    [
        'id' => 15,
        'name' => 'Mitsubisi Lancer',
        'pagename' => 'lancer',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170617_1_lancer.jpg" alt="Mitsubisi Lancer">',
    ],
    [
        'id' => 16,
        'name' => 'Subaru Outback',
        'pagename' => 'outback',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170617_1_outback.jpg" alt="Subaru Outback">',
    ],
    [
        'id' => 17,
        'name' => 'Lada 2111',
        'pagename' => '21110621',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170621_1_2111.jpg" alt="Lada 2111">',
    ],
    [
        'id' => 18,
        'name' => 'Volkswagen Polo',
        'pagename' => 'polo',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170621_1_polo.jpg" alt="Volkswagen Polo">',
    ],
    [
        'id' => 19,
        'name' => 'BMW X5',
        'pagename' => 'bmwx50621',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170621_1_x5.jpg" alt="BMW X5">',
    ],
    [
        'id' => 20,
        'name' => 'Chevrolet Niva',
        'pagename' => 'nivachevrolet',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170623_1_niva.jpg" alt="Chevrolet Niva">',
    ],
    [
        'id' => 21,
        'name' => 'Lifan X50',
        'pagename' => 'lifanx50',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170623_1_x50.jpg" alt="Lifan X50">',
    ],
    [
        'id' => 22,
        'name' => 'Reno Logan',
        'pagename' => 'renologan',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170716_1_logan.jpg" alt="Reno Logan">',
    ],
    [
        'id' => 23,
        'name' => 'Lada Xray',
        'pagename' => 'ladaxray2707',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170727_6_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 24,
        'name' => 'Skoda Rapid',
        'pagename' => 'rapid2807',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170728_1_rapid.jpg" alt="Skoda Rapid">',
    ],
    [
        'id' => 25,
        'name' => 'Lada Xray',
        'pagename' => 'ladaxray3007',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170730_1_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 26,
        'name' => 'Hyundai Creta',
        'pagename' => 'creta0108',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170801_3_creta.jpg" alt="Hyundai Creta">',
    ],
    [
        'id' => 27,
        'name' => 'Toyota Land Cryiser',
        'pagename' => 'cryiser0809',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170809_3_landcryiser.jpg" alt="Toyota Land Cryiser">',
    ],
    [
        'id' => 28,
        'name' => 'Reno Duster',
        'pagename' => 'duster0810',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170810_1_duster.jpg" alt="Reno Duster">',
    ],
    [
        'id' => 29,
        'name' => 'Reno Sandero',
        'pagename' => 'sandero0820',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170820_1_sandero.jpg" alt="Reno Sandero">',
    ],
    [
        'id' => 30,
        'name' => 'Skoda Ieti',
        'pagename' => 'ieti0826',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170826_1_ieti.jpg" alt="Skoda Ieti">',
    ],
    [
        'id' => 31,
        'name' => 'Hyundai ix35',
        'pagename' => 'ix358831',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170831_3_ix35.jpg" alt="Hyundai ix35">',
    ],
    [
        'id' => 32,
        'name' => 'Lada Xray',
        'pagename' => 'xray0902',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170902_1_xray.jpg" alt="Lada Xray">',
    ],
    [
        'id' => 33,
        'name' => 'Opel Mokka',
        'pagename' => 'mokka0908',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20170908_1_mokka.jpg" alt="Opel Mokka">',
    ],
    [
        'id' => 34,
        'name' => 'Reno Kaptur',
        'pagename' => 'kaptur0802',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20180208_1_kaptur.jpg" alt="Reno Kaptur">',
    ],
    [
        'id' => 35,
        'name' => 'Lada Приора',
        'pagename' => 'priora0802',
        'img' => '<img class="img img--gallery" src="/content/gallery/img/20180208_1_priora.jpg" alt="Lada Priora">',
    ],
];